### ISSUE TITLE
Issue when there is special character in a string

### ISSUE THREAD

**Issue by gyan111** [shuchkin/simplexlsxgen#1]
Thank you for this awesome and simple library.

I have set the encoding to UTF- 8.

The xlsx file returns only random 1 field because there is a "£" sign.

I know this issue is not with the library but may be it can be improved to handle this issue.

**Comment by shuchkin** [comment]
```
<?php
header('Content-Type: text/html; charset=utf-8');
```

**Comment by shuchkin** [comment]
try debug
```php
ini_set('error_reporting', E_ALL );
ini_set('display_errors', 1 );

$data = [
    ['Debug', 123]
]
SimpleXLSXGen::fromArray( $data )->saveAs('debug.xlsx');
```

send me php example

**Comment by shuchkin** [comment]
try 0.9.15

**Comment by gyan111** [comment]
it works.

[debug.xlsx](https://github.com/shuchkin/simplexlsxgen/files/4918539/debug.xlsx)

**Comment by gyan111** [comment]
Than you for the quick response and update.

I confirm that the issue has been fixed.

I was also having issue with "'" character. Like I'm. That issue also fixed.

Thank you @shuchkin so much for your hard work developing this simple package.

A must have package if anyone working with excel.

**Comment by shuchkin** [comment]
thx )
