### ISSUE TITLE
Control of date format - ISO YYYY-MM-DD

### ISSUE THREAD

**Issue by richardpbull** [shuchkin/simplexlsxgen#10]
This is wonderfully simple! Thank you. I have a question, which is not a bug.

Is there anyway to avoid an ISO date format being turned into an excel date?

The application I have requires the XLS file to be uploaded automatically with this format in place. 

Thank you for your work!

**Comment by shuchkin** [comment]
good question

**Comment by thepushkarraj** [comment]
I also want to ask the same!!

**Comment by shuchkin** [comment]
more control and formatting
https://github.com/PHPOffice/PhpSpreadsheet

**Comment by richardpbull** [comment]
Thanks for coming back with a suggestion. Appreciated. This is more heavy, but does what's needed in less common cases. All the best.

**Comment by shuchkin** [comment]
try 0.9.20
insert \0 as first char to disable type detecton
https://github.com/shuchkin/simplexlsxgen#data-types
