### ISSUE TITLE
Undefined type 'SimpleXLSXGen'

### ISSUE THREAD

**Issue by chrismuntean** [shuchkin/simplexlsxgen#103]
After install using composer and pasting the following example code:
`
        $books = [
            ['ISBN', 'title', 'author', 'publisher', 'ctry' ],
            [618260307, 'The Hobbit', 'J. R. R. Tolkien', 'Houghton Mifflin', 'USA'],
            [908606664, 'Slinky Malinki', 'Lynley Dodd', 'Mallinson Rendel', 'NZ']
        ];
        $xlsx = Shuchkin\SimpleXLSXGen::fromArray( $books );
        $xlsx->saveAs('books.xlsx'); // or downloadAs('books.xlsx') or $xlsx_content = (string) $xlsx 
`

I get the following error:
`Undefined type 'Shuchkin\SimpleXLSXGen'.intelephense(1009)`

At the line:
`$xlsx = Shuchkin\SimpleXLSXGen::fromArray( $books );`

**Comment by shuchkin** [comment]
```require_once __DIR__ . '/simplexlsxgen/src/SimpleXLSXGen.php';```
