### ISSUE TITLE
Output file MIME type is "application/octet-stream"

### ISSUE THREAD

**Issue by richardpbull** [shuchkin/simplexlsxgen#11]
Greetings - 
The application that consumes the excel file I output says: "This file is not an Excel file (application/octet-stream)". I checked with this service: [https://htmlstrip.com/mime-file-type-checker](https://htmlstrip.com/mime-file-type-checker) .
However in the class, it saves the file with the following header.

`header('Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');`

This seems to be best practice, according to: 
https://stackoverflow.com/questions/4212861/what-is-a-correct-mime-type-for-docx-pptx-etc

Can you please help me understand why this is being interpreted as "application/octet-stream"?

Thank you!

**Comment by shuchkin** [comment]
I think your software need XLS, not XLSX
