### ISSUE TITLE
Combining formula and currency formatting

### ISSUE THREAD

**Issue by paulstenning** [shuchkin/simplexlsxgen#112]
Hello,

I need to create a cell with SUM() formula and £ currency formatting but am unsure how to do this.

I know currency is 
`<style nf="&quot;£&quot;#,##0.00">500</style>`
and formula is 
`<f v="135.35">SUM(B1:B2)</f>`
but I can't work out how to combine them. I tried this but it didn't work.
`<f v="135.35" nf="&quot;£&quot;#,##0.00">SUM(B1:B2)</f>`

Can anyone help please?

Thank you,
Paul

**Comment by shuchkin** [comment]
try
```
<f v="135.35"><style nf="&quot;£&quot;#,##0.00">SUM(B1:B2)</style></f>
```

**Comment by DevOlegKosarev** [comment]
> try
> 
> ```
> <f v="135.35"><style nf="&quot;£&quot;#,##0.00">SUM(B1:B2)</style></f>
> ```

Or with float and if negative number red 
<style nf="#,##0.00\ [$£-1];[Red]#,##0.00\ [$£-1]"><f v="135.35">SUM(B1:B2)</f></style>

I'm test it work correctly

![image](https://user-images.githubusercontent.com/109492069/233186980-91618e10-4f44-4254-96af-b316cf7bc1b6.png)
