### ISSUE TITLE
downloadAs will occur corrupted file

### ISSUE THREAD

**Issue by nbastreet** [shuchkin/simplexlsxgen#116]
Hi
I use downloadAs in local server and everything is ok but in website server, result is null and xlsx file is corrupted and empty.

downloadAs function return a string in local but in website server return true!

any suggestion?

**Comment by shuchkin** [comment]
try
```php
SimpleXLSXGen::fromArray([['Hello World!']])->downloadAs('test.xlsx');
exit();
```
also
https://github.com/shuchkin/simplexlsxgen#debug

**Comment by nbastreet** [comment]
with this line and also debug, final result is same and downloaded file is empty(0 bytes)

**Comment by DevOlegKosarev** [comment]
> with this line and also debug, final result is same and downloaded file is empty(0 bytes)
Write to me on Skype (live:.cid.2cfc9abe0eda4af7) and send a file xlxs as generated and a photo of phpinfo() I will see what could be the reason during coffee.

**Comment by shuchkin** [comment]
> with this line and also debug, final result is same and downloaded file is empty(0 bytes)

check remote PHP version PHP 7.0+

**Comment by xaviermdq** [comment]
Hi nbastreet:
May be corrupted header? May be you can capture server output using some packet sniffer to see if server return malformed response. Also check Apache access and error logs.
This is a long shot but check your output buffering configuration and/or avoid sending characters. Try one of these:
1 - avoid text generation and setting headers before calling downloadAs method (check for unintentional blank characters before and after PHP code tags)
2 - enable output buffering making sure to make it cleanable (specially if you can't achieve 1): execute `ob_start();` as your first line of code. If you already use ob_start and it has a third parameter make sure to use PHP_OUTPUT_HANDLER_STDFLAGS constant.
3 - remove already established headers calling `header_remove();` before calling downloadAs method.

**Comment by xaviermdq** [comment]
You can avoid using the fpassthru function by using fread. But it consumes more memory because you basically copy the file from memory to memory and put the content in the output. The method would be:
```php
    public function downloadAs($filename)
    {
        $fh = fopen('php://memory', 'wb');
        if (!$fh) return false;
        if (!$this->_write($fh)) {
            fclose($fh);
            return false;
        }
        $size = ftell($fh);
        header('Content-type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header('Content-Disposition: attachment; filename="' . $filename . '"');
        header('Last-Modified: ' . gmdate('D, d M Y H:i:s \G\M\T', time()));
        header('Content-Length: ' . $size);
        while (ob_get_level()) ob_end_clean();
        fseek($fh, 0);
        $filecontent = fread($fh);
        fclose($fh);
        echo $filecontent;
        return true;
    }
``` 

You may have to rethink the _write method to not use a filestream. For example, you can pass an empty string by reference to the _write method, operate on that value, and echo the value stored in string before exiting the downloadAs method.

**Comment by nbastreet** [comment]
thanks @xaviermdq 
your code need small fix:

`$filecontent = fread($fh,size);`

Thanks very much. it works.
