### ISSUE TITLE
Background color and cell width

### ISSUE THREAD

**Issue by RPort71** [shuchkin/simplexlsxgen#118]
I have been trying to add a background color, but end up with the cell being either white or blue.  My code is:
`<style bgcolor="lightgrey">Text</style>`

Also, is there a way to widen a column?  The client is asking for bolded text in the headers, but some of the text disappears if it is too big for the column.

**Comment by shuchkin** [comment]
Use #D3D3D3 format
```
<style bgcolor="#D3D3D3">Text</style>
```

https://github.com/shuchkin/simplexlsxgen#formatting
```
->setColWidth(1, 50)
```

**Comment by RPort71** [comment]
Thank you!

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen#formatting
see border examples

style your data
```
$data[0][0] = '<style border="#000000">'.$data[0][0].'</style>';
```

**Comment by RPort71** [comment]
Is there a way to apply borders to the whole sheet without looping through the array?

**Comment by shuchkin** [comment]
no

**Comment by RPort71** [comment]
Thanks for your help and for being so responsive.  Everything works great and is really easy to use.
