### ISSUE TITLE
Unable to use multiple sheets

### ISSUE THREAD

**Issue by C14r** [shuchkin/simplexlsxgen#12]
Hello,

I'm reading my xlsx data file with shuchkin/simplexlsx and in this file are multiple sheets. But now I want to generate this file.
But unfortunately I'm not able to write an xlsx-file with multile sheets in it.

Thank you for your work!

**Comment by shuchkin** [comment]
may be in next product cycle
try other tools now
https://github.com/PHPOffice/PhpSpreadsheet

**Comment by C14r** [comment]
Thanks for your quick response. I'll take a look at the project.
