### ISSUE TITLE
Merge on not yet known cells?

### ISSUE THREAD

**Issue by MaStarzi** [shuchkin/simplexlsxgen#120]
Is there a way to merge cells if I do not know where they are? I'm adding rows depending on user input and I need to merge some cells at the very bottom of the added cells. Your formatting information depicts ['MERGE CELLS ....', NULL] which does not work.

->mergeCells('A20:B20') does work but I don't know which row the cells are in so I can't give a specific integer here.

Any Idea?

**EDIT**

I did find a way, which is not very elegant but it works.

```php
$rowNumberToMerge = count($xlsxGivenArray);
$xlsx = \Shuchkin\SimpleXLSXGen::fromArray($xlsxGivenArray)->mergeCells("A$rowNumberToMerge:B$rowNumberToMerge");
```

Looks bad but it works.

**Comment by shuchkin** [comment]
u must control any user input and know how much row there

**Comment by xaviermdq** [comment]
> Is there a way to merge cells if I do not know where they are? I'm adding rows depending on user input and I need to merge some cells at the very bottom of the added cells. Your formatting information depicts ['MERGE CELLS ....', NULL] which does not work.
> 
> ->mergeCells('A20:B20') does work but I don't know which row the cells are in so I can't give a specific integer here.
> 
> Any Idea?
> 
> **EDIT**
> 
> I did find a way, which is not very elegant but it works.
> 
> ```
> $rowNumberToMerge = count($xlsxGivenArray);
> $xlsx = \Shuchkin\SimpleXLSXGen::fromArray($xlsxGivenArray)->mergeCells("A$rowNumberToMerge:B$rowNumberToMerge");
> ```
> 
> Looks bad but it works.

It doesn't look bad and is one of the correct ways of doing it. With mergeCells method you set which ranges WILL BE merged when XLSX file is generated (__toString, saveAs or downloadAs methods). The method is independent of your data (you can set the object, then set merging ranges and then load data with addSheet for example).
