### ISSUE TITLE
1.3.16 seems to have broken compatibility with Libreoffice Calc

### ISSUE THREAD

**Issue by wadih** [shuchkin/simplexlsxgen#125]
Hi,

1.3.16 seems to have broken compatibility with Libreoffice Calc. 

Downgrading to 1.3.15 is working well.

Sample code:

     $PushkinDOB = '1799-07-06';
     $data = [
      ['Datetime as raw string', "\0" . '2023-01-09 11:16:34'],
      ['Date as raw string', "\0" . $PushkinDOB],
      ['Disable type detection', "\0" . '+12345'],
      ['Insert greater/less them simbols', "\0" . '20- short term: <6 month'],
     ];
     Shuchkin\SimpleXLSXGen::fromArray($data)->saveAs('output.xlsx');

Screenshot when using 1.3.15:

![1 3 15](https://github.com/shuchkin/simplexlsxgen/assets/1222066/1fdd5ace-718c-4f1f-8607-379a7675e1f8)

Screenshot when using 1.3.16:

![1 3 16](https://github.com/shuchkin/simplexlsxgen/assets/1222066/a5c0639b-9fa5-4832-adfb-021a41535950)

**Comment by xaviermdq** [comment]
Solution:
Delete lines 370 and 374. Replace the, now, line 371 with:
`$si[] = preg_match('/^\s|\s$/', $s) ? '<si><t xml:space="preserve">'.$s.'</t></si>' : '<si><t>'.$s.'</t></si>';`
The elseif block is now:
```php
...
             } elseif ($cfilename === 'xl/sharedStrings.xml') {
                if (!count($this->SI)) {
                    $this->SI[] = 'No Data';
                }
                $si_cnt = count($this->SI);
                $si = [];
                foreach($this->SI as $s) {
                    $si[] = preg_match('/^\s|\s$/', $s) ? '<si><t xml:space="preserve">'.$s.'</t></si>' : '<si><t>'.$s.'</t></si>';
                }
                $template = str_replace(['{CNT}', '{STRINGS}'], [$si_cnt, implode("\r\n", $si) ], $template);
                $this->_writeEntry($fh, $cdrec, $cfilename, $template);
                $entries++;
... 
```

**Comment by shuchkin** [comment]
fixed, my bad
