### ISSUE TITLE
_x002d_ is replaced by -

### ISSUE THREAD

**Issue by SanjanaHathwar** [shuchkin/simplexlsxgen#127]
I need STF_x002d_Product to be written as it is. How do I stop Unicode decoding?

$data =[['_x002d_','STF_x002d_Product']];
<img width="456" alt="Excel" src="https://github.com/shuchkin/simplexlsxgen/assets/31928996/760ab42f-26a4-41e7-8d91-ca6bf2794c67">

**Comment by SanjanaHathwar** [comment]
I tried that as well doesn't seem to work.
$data =[["\0"."_x002d_","\0".'STF_x002d_Product']];

**Comment by shuchkin** [comment]
use single quotes correctly
```
$data =[["\0".'x002d', 'STF_x002d_Product']
```
<img width="355" alt="Screenshot_969" src="https://github.com/shuchkin/simplexlsxgen/assets/315872/7f9c7d3c-dda2-4305-b6cf-4bb62617bb4c">
];

**Comment by SanjanaHathwar** [comment]
It works for the first but not the second element. Do you have any suggestions for how I might accomplish this for the second element?

**Comment by shuchkin** [comment]
https://stackoverflow.com/questions/3446216/what-is-the-difference-between-single-quoted-and-double-quoted-strings-in-php

**Comment by SanjanaHathwar** [comment]
Hi,
But this doesn't help me at all!
$data =[["\0". 'STF_x002d_Product']]; 
This scenario doesn't work.

**Comment by shuchkin** [comment]
try alternative tools
https://www.google.com/search?q=php+xlsx
