### ISSUE TITLE
Add Hyperlink

### ISSUE THREAD

**Issue by naeimrezaeian** [shuchkin/simplexlsxgen#13]
hi 

how i can add Hyperlink in excel tables . i usedthis code but dose not work 

`include('SimpleXLSXGen.php');
$books = [
    ['ISBN', 'title', 'author', 'publisher', 'ctry' ,'link'],
    [618260307, 'The Hobbit', 'J. R. R. Tolkien', 'Houghton Mifflin', 'USA','=HYPERLINK("https://google.com","Site")'],
    [908606664, 'Slinky Malinki', 'Lynley Dodd', 'Mallinson Rendel', 'NZ','=HYPERLINK("https://google.com","site")']
];

$xlsx = SimpleXLSXGen::fromArray( $books );

$xlsx->downloadAs('table.xlsx');`

**Comment by shuchkin** [comment]
помню, помню
думаю как малой кровью обойтись

**Comment by Paulsky** [comment]
@naeimrezaeian did you find a solution for this?

**Comment by psycho3069** [comment]
> помню, помню
> думаю как малой кровью обойтись

English please  -_-

**Comment by shuchkin** [comment]
try 1.0.10

```php
$data = [
  [ 'hyperlink 1', 'https://ya.ru' ],
  [ 'hyperlink 2', '<a href="https://smspilot.ru/">SMSPILOT WEB2SMS</a>' ],
];
SimpleXLSXGen::fromArray( $data )->download();
```
