### ISSUE TITLE
Can not get formats to work

### ISSUE THREAD

**Issue by devaabhik** [shuchkin/simplexlsxgen#130]
Grat an easy to use XMLWriter for PHP, But canot pass format data to Writter, it is ignored..

Headers Row
$Excel [] =
['Mes','Fecha', 'NumCFDI', 'UsoCFDI', 'FP', 'MP', 'Complemento', 'FechaCom', 'Nombre', 'RFC', 'Importe', 'Tasa', 'IvaTrasl', 'ISSRRet', 'IVARet', 'Total', 'Observac', 'DescrProd', 'Moneda', 'TipoCambio', 'IVARet16', 'IVARet8', 'IVARet6', 'RetIEPS', 'TrasIVA16', 'TrasIVA8', 'TrasIVA6', 'TrasIEPSAc'];

Data Rows:
		$Excel [] =  [
			($CFDI['ID']),
			($CFDI['Fecha']),
			($CFDI['ID']),
			($CFDI['UsoCFDI']),
			(CFDI['FormaPago']),
			($CFDI['MetodoPago']),
			("Pendiente"),
			("Pendiente"),
			($CFDI['NombreEmisor']),
			($CFDI['RFCEmisor']),
			([$CFDI['Total']]),
			(['Bold',"Pendiente"]),
			(['Float',$TrasIVAAc]),
			($ISRRetAc  ),
			($TrasIVAAc),
			(['Currency $',$Total]),
			(""),
			($DescMax),
			($CFDI['Moneda']),
			($CFDI['TipoCambio']),
			($RetIVA16),
			($RetIVA8),
			($RetIVA6),
			($RetIEPS),
			($TrasIVA16),
			($TrasIVA8),
			($TrasIVA6),
			($TrasIEPSAc)		];

	$xlsx = Shuchkin\SimpleXLSXGen::fromArray( $Excel );
	$xlsx->autoFilter('A1:'.'AB'.count($Excel));
	$xlsx->saveAs("ExcelTest". rand(100,999).".xls");

Used parrnteses for each item as exterior Square brackets would complain about a cmoa on each item.

There are only two cell datas wit format , but it does no go trough..

Thanks in advance

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen#formatting
