### ISSUE TITLE
Adding Line Break in Cell

### ISSUE THREAD

**Issue by maulvieyazid** [shuchkin/simplexlsxgen#133]
Hi, first of all, thank you for creating this awesome package, i really love it, its so simple to use
But, i have a question, 
Is there any format that i can use to add line break in my text cell?
Thank you

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen#formatting

**Comment by VaraldiQ** [comment]
Hi, great job, but it seems the breakline is not working for me.
I merged cells B1:H1, put them in bold, centered and size 16, then I put some \n but it displayes the "\n" instead of breaking line.
I've tried \r, \n, \r\n, all didn't work.
What should I do?

**Comment by shuchkin** [comment]
use ```<wraptext>```

**Comment by VaraldiQ** [comment]
This doesn't change anything in my case. I tried with and without, no difference. Only the trick I wrote did something

**Comment by shuchkin** [comment]
See difference " and ' quotes
