### ISSUE TITLE
downloadAs or saveAs -> corrupted file

### ISSUE THREAD

**Issue by garetjax76** [shuchkin/simplexlsxgen#135]
Hi, first of all I've used SimpleXLSXgen without problems on a ubuntu LAMP system for years now.
I'm now trying to use it also on a IBM i server PHP installation (afaik proprietary linux ppc64 + apache 2.4) that already uses some extensions (like MPDF) without issues, but all I can obtain are corrupted files.

I've tried multiple advices I've found on the web without success.
Attached is a file obtained with the standard example code:
```
require __DIR__ . '/vendor/autoload.php';
$books = [
	['ISBN', 'title', 'author', 'publisher', 'ctry' ],
	[618260307, 'The Hobbit', 'J. R. R. Tolkien', 'Houghton Mifflin', 'USA'],
	[908606664, 'Slinky Malinki', 'Lynley Dodd', 'Mallinson Rendel', 'NZ']
];
$xlsx = Shuchkin\SimpleXLSXGen::fromArray( $books );
$xlsx->downloadAs('books.xlsx');
exit();
```

Opening the files with 7zip they seem alright, but excel can't open them.
[books (7).xlsx](https://github.com/shuchkin/simplexlsxgen/files/13635834/books.7.xlsx)

If I use var_dump, the data seems ok:

`object(Shuchkin\SimpleXLSXGen)#4 (25) { ["curSheet"]=> int(0) ["defaultFont":protected]=> string(7) "Calibri" ["defaultFontSize":protected]=> int(10) ["rtl":protected]=> bool(false) ["sheets":protected]=> array(1) { [0]=> array(7) { ["name"]=> string(6) "Sheet1" ["hyperlinks"]=> array(0) { } ["mergecells"]=> array(0) { } ["colwidth"]=> array(0) { } ["autofilter"]=> string(0) "" ["frozen"]=> string(0) "" ["rows"]=> array(3) { [0]=> array(5) { [0]=> string(4) "ISBN" [1]=> string(5) "title" [2]=> string(6) "author" [3]=> string(9) "publisher" [4]=> string(4) "ctry" } [1]=> array(5) { [0]=> int(618260307) [1]=> string(10) "The Hobbit" [2]=> string(16) "J. R. R. Tolkien" [3]=> string(16) "Houghton Mifflin" [4]=> string(3) "USA" } [2]=> array(5) { [0]=> int(908606664) [1]=> string(14) "Slinky Malinki" [2]=> string(11) "Lynley Dodd" [3]=> string(16) "Mallinson Rendel" [4]=> string(2) "NZ" } } } } ["template":protected]=> array(10) { ["_rels/.rels"]=> string(596) " " ["docProps/app.xml"]=> string(286) " 0 {APP} {COMPANY} {MANAGER} " ["docProps/core.xml"]=> string(859) " {DATE} {TITLE} {SUBJECT} {AUTHOR} {LAST_MODIFY_BY} {KEYWORD} {DESCRIPTION} {CATEGORY} {LANGUAGE} {DATE} 1 " ["xl/_rels/workbook.xml.rels"]=> string(167) " {RELS} " ["xl/worksheets/sheet1.xml"]=> string(341) " {SHEETVIEWS} {COLS} {ROWS} {AUTOFILTER}{MERGECELLS}{HYPERLINKS}" ["xl/worksheets/_rels/sheet1.xml.rels"]=> string(169) " {HYPERLINKS}" ["xl/sharedStrings.xml"]=> string(177) " {STRINGS}" ["xl/styles.xml"]=> string(375) " {NUMFMTS} {FONTS} {FILLS} {BORDERS} {XF} " ["xl/workbook.xml"]=> string(279) " {SHEETS}" ["[Content_Types].xml"]=> string(1013) " {TYPES}" } ["NF":protected]=> array(3) { [164]=> string(15) "#,##0.00\ "₽"" [165]=> string(14) "[$$-1]#,##0.00" [166]=> string(18) "#,##0.00\ [$€-1]" } ["NF_KEYS":protected]=> array(3) { ["#,##0.00\ "₽""]=> int(164) ["[$$-1]#,##0.00"]=> int(165) ["#,##0.00\ [$€-1]"]=> int(166) } ["XF":protected]=> array(2) { [0]=> array(8) { [0]=> int(0) [1]=> int(0) [2]=> int(0) [3]=> int(0) [4]=> int(0) [5]=> int(0) [6]=> string(0) "" [7]=> int(0) } [1]=> array(8) { [0]=> int(0) [1]=> int(0) [2]=> int(0) [3]=> int(16) [4]=> int(0) [5]=> int(0) [6]=> string(0) "" [7]=> int(0) } } ["XF_KEYS":protected]=> array(2) { ["0-0-0-0-0-0--0"]=> int(0) ["0-0-0-16-0-0--0"]=> int(1) } ["BR_STYLE":protected]=> array(14) { [0]=> string(4) "none" [1]=> string(4) "thin" [2]=> string(6) "medium" [3]=> string(6) "dashed" [4]=> string(6) "dotted" [5]=> string(5) "thick" [6]=> string(6) "double" [7]=> string(4) "hair" [8]=> string(12) "mediumDashed" [9]=> string(7) "dashDot" [10]=> string(13) "mediumDashDot" [11]=> string(10) "dashDotDot" [12]=> string(16) "mediumDashDotDot" [13]=> string(12) "slantDashDot" } ["SI":protected]=> array(0) { } ["SI_KEYS":protected]=> array(0) { } ["extLinkId":protected]=> int(0) ["title":protected]=> string(0) "" ["subject":protected]=> string(0) "" ["author":protected]=> string(0) "" ["company":protected]=> string(0) "" ["manager":protected]=> string(0) "" ["description":protected]=> string(0) "" ["application":protected]=> string(22) "Shuchkin\SimpleXLSXGen" ["keywords":protected]=> string(0) "" ["category":protected]=> string(0) "" ["language":protected]=> string(5) "en-US" ["lastModifiedBy":protected]=> string(0) "" }`

Honestly can't figure out what more I can do.
Thanks for the support.

**Comment by garetjax76** [comment]
Updated now, same problem.
Here attached is a file generated with 1.3.19.
[pippo-2023-12-11_19-34-15.xlsx](https://github.com/shuchkin/simplexlsxgen/files/13639678/pippo-2023-12-11_19-34-15.xlsx)
Thanks.

**Comment by garetjax76** [comment]
Sorry, just to be coherent with the first example, here's the same basic book-example.
[books (18).xlsx](https://github.com/shuchkin/simplexlsxgen/files/13639732/books.18.xlsx)

**Comment by shuchkin** [comment]
1.3.20

**Comment by garetjax76** [comment]
Perfect, now it works.
Thanks!!!
