### ISSUE TITLE
The autoresize of columns doesn't work properly when the first row has a different (bigger) font size than the rest of the rows

### ISSUE THREAD

**Issue by merkiw** [shuchkin/simplexlsxgen#136]
The autoresize of columns doesn't work properly when the first row has a different (bigger) font size than the rest of the rows

---

Setup:
PHP - 8.2.4
shuchkin/simplexlsxgen - 1.4.10

---

Preview of issue:

![2024-01-19_12-25](https://github.com/shuchkin/simplexlsxgen/assets/18572506/7e7ad517-6304-41aa-8bd5-67cfc8795ae5)

---

Code to reproduce:

```php

require_once 'vendor/autoload.php';

$transactions = [
    [
        '2023-11-07 11:02:23',
        42.69,
        'EUR',
        'XYD63342535',
        'A good reason',
    ],
    [
        '2023-11-05 21:34:54',
        123.50,
        'EUR',
        'XYD23451593',
        'Not a very good reason',
    ],
    [
        '2023-10-27 10:31:43',
        69,
        'EUR',
        'XYD68296982',
        'A reason',
    ],
];

$formatHeading = fn($v) => "<style font-size=\"20\"><center>{$v}</center></style>";

$rows = array_merge(
    [
        array_map($formatHeading, [
            'Date',
            'Amount',
            'Currency',
            'Reference number',
            'Reason',
        ]),
    ],
    $transactions,
);

$xlsx = Shuchkin\SimpleXLSXGen::fromArray($rows)
    ->downloadAs('transactions.xlsx');
```

**Comment by shuchkin** [comment]
Use
```
$xlsx->setColWidth(0, 40) // 0 - first column
```

**Comment by merkiw** [comment]
> Use
> 
> ```
> $xlsx->setColWidth(0, 40) // 0 - first column
> ```

Thank you for your fast reply! However the idea is not to set a specific width for the columns but to use the auto resize functionality. 

I saw that when calculating the width it currently takes in mind the type of the cell value e.g. string, int, float, date but is it possible to take in mind also the font size?

**Comment by shuchkin** [comment]
https://c-rex.net/samples/ooxml/e1/Part4/OOXML_P4_DOCX_col_topic_ID0ELFQ4.html

BIG headers this is a rare case
in 4 years u first, who want add autosize to this case

if you propose a very easy solution without additional cycles and multi-level conditions, I’ll add it to the class

**Comment by merkiw** [comment]
I'm unable to propose an easy solution for this problem so I'll close the issue
