### ISSUE TITLE
Feature Request: Append to Excel File

### ISSUE THREAD

**Issue by 1of3** [shuchkin/simplexlsxgen#137]
Would it be possible to add an option to append to an Excel File?

I have a situation where a result set is too large to fit in memory and so my script crashes.

If I could select less records and append to an excel file I can get around this issue so thought I would ask the question.

Thanks

John

**Comment by shuchkin** [comment]
1.4.10: no ideas

use csv
```php
$fp = fopen('file.csv', 'w');

$q = mysqli_query($link, "SELECT id,name FROM big_table");
while ($row = mysql_fetch_array($q)) {
    fputcsv($fp, $row);
}

fclose($fp);
header('Location: file.csv');
```
