### ISSUE TITLE
Hyperlink to internal file

### ISSUE THREAD

**Issue by mhkh8367** [shuchkin/simplexlsxgen#139]
Is there any way to create a link to specific internal file located in current location of created excel?

Example:
I have created an excel file named "new.xlsx" and located that in "abc" folder
There is a file named "a123.xlsx" in "abc" folder that contains a sheet named "sheet1"
I want to create a link in "new.xlsx" file that can direct to cell "A3" in sheet "sheet1" of "a123.xlsx" file in "abc" folder

How to create this link by SimpleXLSXGen?

**Comment by shuchkin** [comment]
supported in 1.4.11
see [more examples](https://github.com/shuchkin/simplexlsxgen?tab=readme-ov-file#more-examples)

**Comment by mhkh8367** [comment]
> supported in 1.4.11 see [more examples](https://github.com/shuchkin/simplexlsxgen?tab=readme-ov-file#more-examples)
> 
> ```
> SimpleXLSX::fromArray([
>     ['relative', '<a href="..\books.xlsx#\'Sheet 2\'!A1">link to second sheet in other book</a>'],
> ])->saveAs('hyperlinks.xlsx');
> ```

Thank you very much. Well done :)
