### ISSUE TITLE
http2

### ISSUE THREAD

**Issue by mankowitz** [shuchkin/simplexlsxgen#143]
I am using Apache 2.4.52, php-8.1.2 with fpm on Ubuntu. When I enable http2,  downloadAs() no longer works. Chrome error is "check your internet connection"

Steps to repeat
    # a2enmod http2

When I disable http2, it works again
    # a2dismod http2

I've tried prefacing the downloadAs command with ob_start(), but no luck

**Comment by shuchkin** [comment]
In my nginx http2 works.
Try download any other generated content https://stackoverflow.com/questions/4371748/create-a-text-file-for-download-on-the-fly

**Comment by shuchkin** [comment]
exit() ?

**Comment by mankowitz** [comment]
`exit()` solved it. Thanks. I'm not sure why it's a problem with http2 and not with http1.
