### ISSUE TITLE
Apply number format in cell which contains formula

### ISSUE THREAD

**Issue by a64444** [shuchkin/simplexlsxgen#147]
I am trying to apply a number format on a cell which contains a formula bu it results in a corrupted file.
When am tryting to open the spreadsheet, excel repairs it and the file contents appear as they should.
<style nf="#,##0.00"><f>SUM(A1:B1)</f></style>.

**Comment by shuchkin** [comment]
```php
$data = [
    [1,2,'<style nf="#,##0.00"><f v="3.00">SUM(A1:B1)</f></style>']
];
SimpleXLSXGen::fromArray($data)->saveAs('test_nf_and_formula.xlsx');
```

**Comment by a64444** [comment]
Thank you very much, now works.
Very good work!
