### ISSUE TITLE
SimpleXLSXGen generate a file that can't be open by Excel

### ISSUE THREAD

**Issue by antonellorossi** [shuchkin/simplexlsxgen#149]
This is my code 

$xlsx = Shuchkin\SimpleXLSXGen::fromArray( $dati_tabella );
$xlsx->downloadAs('Questionario.xlsx');

$dati_tabella is an array and it's not empty.

But after download "Questionario.xlsx" Excel open it complete blank or with an error to load data.

I have the last version of this library.

**Comment by shuchkin** [comment]
Try exit() after diwnloadAs()

**Comment by antonellorossi** [comment]
Works !!! Thank you.
