### ISSUE TITLE
Missing feature: Multi-line cells / line breaks missing

### ISSUE THREAD

**Issue by filbe** [shuchkin/simplexlsxgen#15]

**Comment by shuchkin** [comment]
use \r\n and check cell value in top editbox in excel

**Comment by surinderrawat1987** [comment]
I dont understand the fix. How is that a fix. The newlinme in a cell feature is missing

**Comment by shuchkin** [comment]
row autoheight disabled
newlines in cells saved as is, but don't shows
try resize row height

**Comment by cyberzilla** [comment]
> row autoheight disabled newlines in cells saved as is, but don't shows try resize row height

@shuchkin I have extracted the excel file which has line breaks / wrap text in the cell, in `xl\style.xml` there is a line like this
```
<xf numFmtId="0" fontId="1" fillId="0" borderId="0" xfId="0" applyFont="1" applyAlignment="1">
             <alignment vertical="top" wrapText="1"/>
</xf>
```
how to implement it into this class?

**Comment by shuchkin** [comment]
try 1.2.15
see `wraptext` https://github.com/shuchkin/simplexlsxgen#formatting

**Comment by maruhe** [comment]
<wraptext> doesnt work for me
simplexlsxgen works great for my needs, just I have mulit-line-text in colum
it tried using \n and \r\n and also added the <wraptext>-tags but when I open the file in excel (LibreOffice) I only see one text-line and need to ajust the row-heights manually
would be quite cool to set row-height to auto

**Comment by shuchkin** [comment]
> doesnt work for me simplexlsxgen works great for my needs, just I have mulit-line-text in colum it tried using \n and \r\n and also added the -tags but when I open the file in excel (LibreOffice) I only see one text-line and need to ajust the row-heights manually would be quite cool to set row-height to auto

excel don't have "rowautoheight" option out of the box

this is opensource, go :)
