### ISSUE TITLE
SimpleXLSXGen.php:326

### ISSUE THREAD

**Issue by ngothoai** [shuchkin/simplexlsxgen#151]
PHP Warning:  Cannot modify header information - headers already sent by (output started at

I am using SimpleXLSXGen for download file excel but it error

Error : SimpleXLSXGen.php:326

https://prnt.sc/67JDtPviNt0l
https://prnt.sc/K2RalM6jD1nS

Please check this issue

Thanks

**Comment by shuchkin** [comment]
https://stackoverflow.com/questions/8028957/how-to-fix-headers-already-sent-error-in-php
use ```exit()```
