### ISSUE TITLE
adjust column size to accommodate uppercase letters

### ISSUE THREAD

**Issue by florian08fr** [shuchkin/simplexlsxgen#157]
hello.
thanks for your class, it's really useful.
when a cell contains text in uppercase only, a column width adjustment could be done line 831:
https://github.com/shuchkin/simplexlsxgen/blob/a44de02fe239e45cc86469b33509b542e73abeb8/src/SimpleXLSXGen.php#L831
by adding something like:
`$vl+=intval(0.2*mb_strlen(preg_replace('![^A-Z]+!', '', $v)));`

Also, it could be very useful to have a parameter that deactivates the limitation of the column width to the value 60 in line 961, or alternatively that the value 60 be customizable in the default variables, without having to define a fixed column width in our php script:
https://github.com/shuchkin/simplexlsxgen/blob/a44de02fe239e45cc86469b33509b542e73abeb8/src/SimpleXLSXGen.php#L961

best regards.

**Comment by shuchkin** [comment]
just use setColWidth
https://github.com/shuchkin/simplexlsxgen/blob/a44de02fe239e45cc86469b33509b542e73abeb8/src/SimpleXLSXGen.php#L1100
