### ISSUE TITLE
Thousands separator

### ISSUE THREAD

**Issue by knikke** [shuchkin/simplexlsxgen#158]
Hey again!

I would like to use a space as the thousands separator in Excel, so the formatted value would be, for example:

number_format(1200000.35, '2', '.', ' ')

Currently, the library interprets this as a string, which causes the cell to be treated as a General type field instead of a Number type. In Finland, a space is used as the thousands separator, so it is important to get this right. Can you help?

Thanks!

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen?tab=readme-ov-file#data-types

`<style nf="# ###0,00">12345678.12345</style>`

`12 345 678,12`

https://support.microsoft.com/en-us/office/number-format-codes-5026bbd6-04bc-48cd-bf33-80f18b4eae68

**Comment by knikke** [comment]
Perfect! Thank you!
