### ISSUE TITLE
how do I freeze the first row with the freezePanes() method?

### ISSUE THREAD

**Issue by pbiron** [shuchkin/simplexlsxgen#159]
In the More Examples(https://github.com/shuchkin/simplexlsxgen?tab=readme-ov-file#more-examples) section there is an example of how to freeze panes, e.g.,

```
// Freeze rows and columns from top-left corner up to, but not including,
// the row and column of the indicated cell
$xlsx->freezePanes('C3');
```

However, when I try that it seems to freeze all **columns** up until _C3_.

I imagine there is a syntax for the parameter to the `freezePanes()` method that allows for freezing rows (in particular, the 1st row), but for the life of me I can't figure out what to pass to that method for freeze rows.

**Comment by shuchkin** [comment]
added comment to example
`$xlsx->freezePanes('B2'); // B1 - freeze first column, A2 - freeze top row`

**Comment by pbiron** [comment]
thank you!!
