### ISSUE TITLE
Error when using download or downloadAs

### ISSUE THREAD

**Issue by marcorensch** [shuchkin/simplexlsxgen#16]
When i am doing it like described in your quickstart info Excel throws an error when try to open the generated xlsx file via download or downloadAs...
NOT OK:
`$data = [['Integer', 123],['Float', 12.35]];
$xlsx = SimpleXLSXGen::fromArray( $data );
$status = $xlsx->downloadAs('export.xlsx');`

Excel can "fix" the bug all data are visible...

But when i am doing it like this:
`$data = [['Integer', 123],['Float', 12.35]];
$xlsx = SimpleXLSXGen::fromArray( $data );
$status = $xlsx->saveAs('export.xlsx');`

and open / or download the file the error is not not thrown.
My Workaround now is to create the excel and then download it manually with a button. 

This happens on my local environment (MAMP Pro and PHP 7.4)

**Comment by shuchkin** [comment]
```
$xlsx->downloadAs('export.xlsx');
exit();
```
