### ISSUE TITLE
Adding images

### ISSUE THREAD

**Issue by cabesd** [shuchkin/simplexlsxgen#17]
Hi !
I would love to help you out with this implementation but once I started looking at the code I realize I know nothing about XLS formatting.
Is something you would like to add in the near future?

The reason I use your implementation over PhpSpreadsheet is that yours is lightweight, simple and also they require PHP >= 7.2

Thank you!

**Comment by shuchkin** [comment]
no, Ezequiel, any drawings in tables not our way
