### ISSUE TITLE
simply text format

### ISSUE THREAD

**Issue by ATM-NET** [shuchkin/simplexlsxgen#19]
Чувак, это супер!
Как насчет простейшего форматирования текста в ячейке? "Адрес ячейки", "размер шрифта" и "жирный / курсив" было бы достаточно. 
Или использовать встроенный стиль экселя в такой-то ячейке.

**Comment by shuchkin** [comment]
> Dude, this is super!
> How about the simplest formatting of text in a cell? "Cell address", "font size" and "bold / italic" would suffice.
> Or use the built-in Excel style in such and such a cell.

Please use pull request to add this features )

**Comment by romikkazan** [comment]
I support! Simple formatting is missing! I could not add a pull request, so I write here

**Comment by shuchkin** [comment]
try 1.0.10
