### ISSUE TITLE
When opening the file in excel, does it give a message that needs to be repaired?

### ISSUE THREAD

**Issue by EwertonDutra** [shuchkin/simplexlsxgen#20]
When opening the file in excel, does it give a message that needs to be repaired?

Have you seen any messages like that?

**Initial message**
![2021-01-24](https://user-images.githubusercontent.com/13201575/105635200-96737900-5e40-11eb-88ae-6ed41feebf7e.png)
**Result**
![2021-01-24 (1)](https://user-images.githubusercontent.com/13201575/105635197-95424c00-5e40-11eb-9d8f-fa4ad8b2582f.png)
**LOG**
![2021-01-24 (2)](https://user-images.githubusercontent.com/13201575/105635199-95dae280-5e40-11eb-8bc2-52759588d9f3.png)

[producao-x-vendas.xlsx](https://github.com/shuchkin/simplexlsxgen/files/5862550/producao-x-vendas.xlsx)

Only in this file that gave this. Others that I generated are normal!

**Comment by shuchkin** [comment]
in your generated XLSX I fond values like <v>1,12</v>, right way is <v>1.12</v>
1) u has used other generator
or
2) u has used "\0" prefix to write raw XML string

**Comment by EwertonDutra** [comment]
I use the function 

`number_format($credit, 2, ',', '.')`

More in another spreadsheet I use it too and it doesn't give an error!
I'm just using the generator

```
$xlsx = SimpleXLSXGen::fromArray($linhas);
$xlsx->saveAs('arquivos/producao-x-vendas.xlsx');
```

And I don't change the generated file (or to be generated) at all

**Comment by shuchkin** [comment]
try 0.9.23, there disabled locale dependencies


(float) 1.23 - good value to parser, saved in xlsx as float
(string) 1234.56 - good value, saved as float
(string) 1.234,56 - bad value, saved as string

**Comment by EwertonDutra** [comment]
Wonderful,

I updated the package and no longer shows the repair message

Thank you for your help
