### ISSUE TITLE
Procent or Percent?

### ISSUE THREAD

**Issue by bcraigie** [shuchkin/simplexlsxgen#22]
Hi, sorry if this is the wrong place to mention this - I shall remove this if you like.  In the Example, there is :

$data = [
    ['Integer', 123],
    ['Float', 12.35],
    ['Procent ', '12%'],
    ['Datetime', '2020-05-20 02:38:00'],
    ['Date','2020-05-20'],
    ['Time','02:38:00'],
    ['String', 'Long UTF-8 String in autoresized column'],
    ['Disable Type Detection', "\0".'2020-10-04 16:02:00']
];

Should Procent be Percent?

:-)

**Comment by shuchkin** [comment]
fixed in 0.9.24

just EN "Percent" = RU "Procent"
