### ISSUE TITLE
I see output like \�&�x�5�;�*D��3�A� on page

### ISSUE THREAD

**Issue by imrannazirbhat** [shuchkin/simplexlsxgen#28]
Hello,

I see output like \�&�x�5�;�*D��3�A� on page while tring to download excelsheet. Am I missing anything?

**Comment by shuchkin** [comment]
use exit() afer $xlsx->downloadAs

**Comment by imrannazirbhat** [comment]
> use exit() afer $xlsx->downloadAs

Thanks a lot!
