### ISSUE TITLE
Error when parsing 23:06:11

### ISSUE THREAD

**Issue by franceq** [shuchkin/simplexlsxgen#3]
Hi,
i wanted to save time "23:06:11" as a string to a cell, but the lib crashed. 
called 
`public function date2excel($year, $month, $day, $hours=0, $minutes=0, $seconds=0)`
with params (0, 0, 0, 23, 6, 11)
variable $year is changed to -1 in the else statement, then
```
$century = substr($year,0,2);
$decade = substr($year,2,2);

$excelDate = floor((146097 * $century) / 4) + floor((1461 * $decade) / 4) + floor((153 * $month + 2) / 5) + $day + 1721119 - $myExcelBaseDate + $excel1900isLeapYear;
```

the line with $excelDate crashes because of non numeric value of century (the sign minus).

I tried to do a fix and set the $year back to 0 if negative and it stoped to crash, but the cell was kind of nonsense, it was datetime format with year 0001 or someting like that. I consider this as a bad behaviour and i solved the problem with commenting 
```
/*elseif ( preg_match('/^(\d\d):(\d\d):(\d\d)$/', $v, $m ) ){
							$cv = $this->date2excel(0,0,0,$m[1],$m[2],$m[3]);
							$cs = 4; // [14] mm-dd-yy
						}*/
```
I think this pattern should not be considered as a datetime even pure string is much better solution, TimeSpan would be optimal, but I am not sure, if it is supported.

BG, Franceq

**Comment by shuchkin** [comment]
try 0.9.16

**Comment by franceq** [comment]
Works fine! Thanks for lightning fast response and resolving of issue.
