### ISSUE TITLE
Method or parameter for disabling type detection

### ISSUE THREAD

**Issue by rusproject** [shuchkin/simplexlsxgen#31]
Hello! Could you implement something like this inside the class? Thanks!
```
public function disableTypeDetection() {
		foreach ($this->sheets as &$sheet)
			foreach ($sheet['rows'] as &$row)
				foreach ($row as &$cell)
					$cell = chr(0) . $cell;
		return $this;
	}
```
P.S. Can't do pull requests, sorry

**Comment by shuchkin** [comment]
I don't want add this code to base class

**Comment by rusproject** [comment]
Given code was an example, I believe there is a better way to do what I mentioned - option for simple disabling type detection. Any chance you could add such feature?

**Comment by shuchkin** [comment]
All numbers/dates as string in Excel book is bad way, it does not correspond to business objectives (search/sorting/analize....)
use php types int, float, Datetime
or use alternative library
https://github.com/mk-j/PHP_XLSXWriter
