### ISSUE TITLE
Suggestion: able to set cell text and background colors

### ISSUE THREAD

**Issue by marcrobledo** [shuchkin/simplexlsxgen#33]
First of all, thanks for this library, it's what I really was looking for: a lightweight single file library for basic xlsx building in PHP.

There is a little feature that is missing and is a must IMHO: being able to set cell text and background colors.

There could be a bunch of predefined basic colors defined in the internal `styles.xml`. Then user could just type:
```['My label', '<red>My value</red>']```
while adding cells to the array.

**Comment by NeuwenWolf** [comment]
I'd like to also express that this would be useful.

**Comment by NeuwenWolf** [comment]
Is there any chance you'd be willing to share what you've got so far on that front?

**Comment by marcrobledo** [comment]
I can, but it's just a little hack for a single color.
Adding other predefined colors shouldn't be hard. However, as simplexlsxgen is coded, it would be hard to add custom colors. It would need an overhaul in the styles xml building in order to make it possible.

@shuchkin are you interested on this?

**Comment by shuchkin** [comment]
class MyXLSXGen extends SimpleXLSXGen {}

**Comment by ProjectLinde37** [comment]
> class MyXLSXGen extends SimpleXLSXGen {}
Where can we find de class MyXLSXGen ?

**Comment by shuchkin** [comment]
:)
you have to write this class

**Comment by shuchkin** [comment]
current supported formatting
https://github.com/shuchkin/simplexlsxgen#formatting

**Comment by mrjemson** [comment]
Have added text color capability in my fork and submitted a pull request for the same.
https://github.com/mrjemson/simplexlsxgen

Have done some basic testing with adding fill options also and will add this at a future date.

NB: Great library @shuchkin very elegant.

**Comment by mrjemson** [comment]
Have also now added background color fill options into above fork.
