### ISSUE TITLE
Broken generation: if string contents "https"

### ISSUE THREAD

**Issue by pulavska** [shuchkin/simplexlsxgen#35]
https://github.com/shuchkin/simplexlsxgen/blob/4f375a4c30adc1d6eed2f3d1032d6673e1d607a0/src/SimpleXLSXGen.php#L499

If I try to save a string like this `'\"https://test.rexx.com/de/vpos\"'` the file will be broken.

<img width="435" alt="Screenshot 2021-05-19 at 01 05 09" src="https://user-images.githubusercontent.com/8693877/118729746-1d5cbf00-b83f-11eb-8d6f-8bf7f0b12bec.png">

I didn't debug deep, but the commenting SimpleXLSXGen.php file lines from 499 to 502 helps.

**Comment by shuchkin** [comment]
try 1.0.12
