### ISSUE TITLE
Suggestion: Able to insert formulas

### ISSUE THREAD

**Issue by NeuwenWolf** [shuchkin/simplexlsxgen#38]
In my testing with OpenOffice, simply inserting a formula string doesn't do it.
E.g. `=AVERAGE(B2:H2)` inserted into a cell, is not inserted as a usable formula.

**Comment by shuchkin** [comment]
try alternatives
https://github.com/search?l=PHP&q=xlsx&type=Repositories

https://github.com/PHPOffice/PhpSpreadsheet
```php
$spreadsheet->getActiveSheet()->getCell('E11')->getCalculatedValue();
```
