### ISSUE TITLE
Unable to call saveAs / downloadAs / etc methods more than once

### ISSUE THREAD

**Issue by no-name-here** [shuchkin/simplexlsxgen#41]
Dunno if its a bug or an undocumented feature, but if you write something like this:
$xlsx = SimpleXLSXGen::fromArray($data);
$xlsx->saveAs('data1.xlsx');
$xlsx->saveAs('data2.xlsx');

second saveAs() call will generate several warnings and data2.xlsx file will be corrupted:
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in SimpleXLSXGen.php on line 248
PHP Warning:  count(): Parameter must be an array or an object that implements Countable in SimpleXLSXGen.php on line 251
PHP Warning:  implode(): Invalid arguments passed in SimpleXLSXGen.php on line 252

Probably, at least SI and SI_KEYS should be set to their devault values (empty array) at the beginning of the _write() method, not in constructor.
Or at least mention it in documentation :)

Thanks in advance.

**Comment by shuchkin** [comment]
fixed in 1.0.21

**Comment by no-name-here** [comment]
Thanks! :)
