### ISSUE TITLE
Im getting an error

### ISSUE THREAD

**Issue by amitwaveproject** [shuchkin/simplexlsxgen#45]
Fatal error: Call to undefined function mb_strlen() in **/SimpleXLSXGen.php on line 345
what can i do?

**Comment by shuchkin** [comment]
https://www.php.net/manual/en/mbstring.installation.php

or replace all mb_strlen($data, '8bit'); to strlen( ... )


PS: why I use mb_strlen see here https://www.php.net/manual/en/mbstring.overload.php
