### ISSUE TITLE
Problem to generate xlsx with accented letters or Ç

### ISSUE THREAD

**Issue by fredgnf** [shuchkin/simplexlsxgen#47]
When the content of the array has strings with accented letters (Á é í ã ....) or Ç the xlsx generated is malformed. 

I notice when i tryed to generate  a xlsx why the array:

Array ( [0] => Array ( 
[0] => Número do Contrato 
[1] => Empenho 
[2] => Objeto 
[3] => Fornecedor 
[4] => Data de Publicação
[5] => Data de Assinatura 
[6] =>Data de Início de Vigência 
[7] => Data de Fim De Vigência 
[8] => Valor do Contrato  ) )

I try to use utf8_encode and utf8_decode functions, but it does not worked.

**Comment by shuchkin** [comment]
Encoding must be UTF-8!
```php
$data = [
  ['Número do Contrato', 'Empenho', 'Objeto', 'Fornecedor', 'Data de Publicação', 'Data de Assinatura', 'Data de Início de Vigência', 'Data de Fim De Vigência',  'Valor do Contrato']
];
SimpleXLSXGen::fromArray( $data, 'Encoding' )->saveAs('Fredgnf_enc.xlsx');
```
[Fredgnf_enc.xlsx](https://github.com/shuchkin/simplexlsxgen/files/7590585/Fredgnf_enc.xlsx)

* save to file your data, and open in text editor to validate encoding

**Comment by fredgnf** [comment]
You are right. Sorry.

**Comment by fredgnf** [comment]
And thanks for be quick to respond.
