### ISSUE TITLE
Errors with hyperlinks

### ISSUE THREAD

**Issue by c0usin** [shuchkin/simplexlsxgen#50]
Hello,

I'm trying to export data from database. If I don't have any hyperlinks in the data the export will be generated and can be opened successfully with Excel.

When the data has hyperlinks with parameters like mydomain.com/param1=xx&param2=ss... then xlsx is generating the data without problem, but when I try to open with Excel, getting an error, the file is corrupted, would you try to repair, if yes it tries but without success. The file can't be opened.

I tried almost everything, converting data ti UTF-8, some other encodings, didn't work.
If I'm using urlencode for the link, than Excel can open the file, but the link it looks like param1%2Fxx%3D%2Fss and so on, every special character will be encoded.

My clients are not accepting those caracters,
what would I do?

**Comment by shuchkin** [comment]
try to find the error yourself, check regex-es in SompleXLSXGen.php

**Comment by shuchkin** [comment]
contribute to an open source project
