### ISSUE TITLE
Problem with date year < 1900 and year = 0000

### ISSUE THREAD

**Issue by fapth** [shuchkin/simplexlsxgen#51]
Hello there is a Problem with date's which are smaller then 1900 like '1876-01-30'
and also Problem with year "0000-00-00".
Last one I fixed it by 
if ( $year === 0 || (int) $year == 0 ) {
	        return $excelTime;
        }

**Comment by shuchkin** [comment]
fixed in 1.0.23

**Comment by shuchkin** [comment]
use raw values
$cell = "\0".'1985-01-13';

not "german time", there OS date/time/datetime format by default

**Comment by fapth** [comment]
yes I know it's using OS date format. But the Script is changing it automatic. So its Mixing now RAW Types and OS date. So it would be nice to tell the format for both. But this is maybe only an edge case.

**Comment by shuchkin** [comment]
if u have mixed dates <1900 and >1900, then use raw (string) values for all your dates

But the Script is changing it automatic -- setlocale temporary resets LC_NUMERIC to neгtral  for correct cast numbers to strings
