### ISSUE TITLE
Corrupted downloaded xlsx

### ISSUE THREAD

**Issue by binaondrej** [shuchkin/simplexlsxgen#53]
Files generates ok, but problem is when is downloaded. Downloaded file is corrupted and can not be opened. (MS Excel shows message about corrupted file and offers repairing, what doesn't help)

```php
$xlsx = create_event_xlsx($event);
$xlsx->saveAs($event['title'] . '.xlsx');         // ok
$xlsx->downloadAs($event['title'] . '.xlsx');     // corrupted file
```

**Comment by shuchkin** [comment]
use exit()

**Comment by binaondrej** [comment]
Ohh, sorry, I missed this

Thank you
