### ISSUE TITLE
generating decimal number with dott instead of comma

### ISSUE THREAD

**Issue by Miz-373** [shuchkin/simplexlsxgen#57]
hey there,
first wanna thank you for this amazing package, it is really helpfull.
i am trying to generate a xlsx file which contain decimal number such as (0.19) but instead i am getting (0,19).
is there a way to edit this before generating?
Thanks in advance

**Comment by shuchkin** [comment]
there uses default float format - locale based

see Raw Strings https://github.com/shuchkin/simplexlsxgen#data-types

**Comment by shuchkin** [comment]
foreach ( $csv as &row ) {
  $row[ 3 ]  = "\0".$row[3]; // 3 = column
}

**Comment by Miz-373** [comment]
it works.
first of all , i can not be enought thankfull. you gotta know that it is the best Tool worldwide, i love you man really really thanks.
i will post it on my social channels, to let people really know and see how much , easy, fast, and effective tool it is.
with all love from Germany.

**Comment by shuchkin** [comment]
thx )
