### ISSUE TITLE
Change Date Format

### ISSUE THREAD

**Issue by hadyanfadlillah** [shuchkin/simplexlsxgen#59]
Hi, when I insert a date in the array it is automatically changed to 'm/d/yy' format in the generated excel file. How can I configure the format for the date?
thanks, sorry for my broken English.

**Comment by shuchkin** [comment]
date/time saved as numbers and displayed as specified in your OS
pls use raw strings for dates as hack
https://github.com/shuchkin/simplexlsxgen#data-types

```
$data = [
  ['Date as raw string', "\0".'2022-04-25']
];
```
