### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by r4naf** [shuchkin/simplexlsxgen#61]
![image](https://user-images.githubusercontent.com/37614712/168736930-3d89fd4d-b7a3-4131-af4c-07a5e7f7cd61.png)
How to make borders?
Как сделать границы?

**Comment by geost77** [comment]
I am also interested of this. How can create borders - both thin border and thick borders ...

**Comment by c3r38r170** [comment]
Have you tried [formatting](https://github.com/shuchkin/simplexlsxgen#formatting) with [border tag or something like that](https://github.com/shuchkin/simplexlsxgen/blob/199e5691e773b1d49092f0c56c60e05d687b7935/src/SimpleXLSXGen.php#L102)?

That should be in the formatting part of the readme, if possible.

**Comment by shuchkin** [comment]
borders are not currently supported

**Comment by aardabalkan** [comment]
Do you plan to make an update for borders near future? Thanks.

**Comment by aardabalkan** [comment]
Thanks for the response, I hope you may find a tiny time for this. If you have no time, I guess you are working hard, this is good.

**Comment by sarelvdm** [comment]
This would be a useful feature to an excellent product

**Comment by sarelvdm** [comment]
Thank you
