### ISSUE TITLE
Keep %2F from being replaced by forward slash?

### ISSUE THREAD

**Issue by thegodfather001** [shuchkin/simplexlsxgen#62]
Hello,

When I put a URL in as hyperlink simplexlsxgen wants to replace %2F with a forward slash /. I need the %2F to stay as is because that's the way the URL is.

Is it possible to ignore %2F?

Thank you

**Comment by shuchkin** [comment]
```php
$data = [
    ['Percent encoding / %2F in URL', 'https://yandex.ru/search/?text=percent+%2F+encoding']
];
SimpleXLSXGen::fromArray( $data )
    ->saveAs( 'percent_in_url.xlsx');
```
<img width="554" alt="Screenshot_387" src="https://user-images.githubusercontent.com/315872/169785224-4c4eba5b-c25c-410a-8a9b-8bb382d1181c.png">
<img width="340" alt="Screenshot_388" src="https://user-images.githubusercontent.com/315872/169785235-7a4a351e-e0df-43cb-8708-63270e0dbf3e.png">

**Comment by thegodfather001** [comment]
My apologies I wasn't specific it was with a hyperlink + anchor

I'll share the link that I'm having a problem with.

I appreciate your help.

https://firebasestorage.googleapis.com/v0/b/qr-asset-tracking-1c8be.appspot.com/o/sig%2FRdfhkCustomer%20Dropped%20Off1653160271076.jpg?alt=media&token=e45564f0-f9e2-4df3-b28e-097ff45ed390

**Comment by shuchkin** [comment]
```php
$data = [
    ['Href + anchor', '<a href="https://firebasestorage.googleapis.com/v0/b/qr-asset-tracking-1c8be.appspot.com/o/sig%2FRdfhkCustomer%20Dropped%20Off1653160271076.jpg?alt=media&token=e45564f0-f9e2-4df3-b28e-097ff45ed390">Image here</a>']
     ];
SimpleXLSXGen::fromArray( $data )
    ->saveAs( 'percent_in_url_href.xlsx');
```
<img width="1216" alt="Screenshot_390" src="https://user-images.githubusercontent.com/315872/169953126-e2d3d450-510c-48c4-9da4-5ff97361f7ea.png">

**Comment by thegodfather001** [comment]
So it turns out safari was changing it when I clicked the link in the spreadsheet, chrome on windows 10 opened fine.

Thank you!
