### ISSUE TITLE
How to fix/frozen headers?

### ISSUE THREAD

**Issue by SHKEd** [shuchkin/simplexlsxgen#63]
It is necessary to fix the headers for example... How to do it? Maybe I missed something or there is no such possibility?

**Comment by SHKEd** [comment]
> Грязный хак на данный момент (1.2.13) См. XML-шаблон (строка 89) "xl/worksheets/sheet1.xml " и вставить информацию о панели
> 
> ```
> <dimension ref="{REF}"/>...ВСТАВЬТЕ СЮДА ИНФОРМАЦИЮ О ПАНЕЛИ ... {COLS}...
> ```
> 
> Информация о панели для замороженного заголовка
> 
> ```
>  <sheetViews>
>  <sheetView tabSelected="1" workbookViewId="0">
>  <pane ySplit="1" TopLeftCell="A2" activePane="bottomLeft" state="frozen"/>
>  <selection pane="bottomLeft" sqref="A1:XFD1"/>
>  </sheetView>
>  </sheetViews>
> ```
Спасибо! Потихоньку разбираюсь (впервые с xls и уже подсморел) вчера. Таких хаков можно вставить приличное количество - например о списках.... Вообщем, генератор понравился.... Как отблагодарить (в связи с последними событиями карты не работают)? Напишите мне

**Comment by shuchkin** [comment]
https://qiwi.com/n/SHUCHKIN

**Comment by xaviermdq** [comment]
I add frozen functionality doing the following:
- Suppose you want to frozen the first $CF columns (column 0 to $CF-1) and $RF rows (row 0 to $RF-1). If $CF==0, we only have frozen row(s). If $RF==0, we have only frozen column(s). If both are 0, we don't have frozen cells at all.
- In line 93 ('xl/worksheets/sheet1.xml' template), add {SHEETVIEW} before {COLS}
- In line 721 (at the end of _sheetToXML function), add another replacement: {SHEETVIEW} to $SHEETVIEW
- In _sheetToXML function, after the first if (line 487), define $SHEETVIEW as "" if  $CF==0 and $RF==0. Any other case:
* When $CF != 0 and $RF != 0:
	<sheetViews>
		<sheetView tabSelected="1" workbookViewId="0">
			<pane xSplit="{$CF}" ySplit="{$RF}" topLeftCell="{$cell}" activePane="bottomRight" state="frozen"/>
		</sheetView>
	</sheetViews>
* When $CF != 0 and $RF == 0:
	<sheetViews>
		<sheetView tabSelected="1" workbookViewId="0">
			<pane xSplit="{$CF}" topLeftCell="{$cell}" activePane="topRight" state="frozen"/>
		</sheetView>
	</sheetViews>
* When $CF == 0 and $RF != 0:
	<sheetViews>
		<sheetView tabSelected="1" workbookViewId="0">
			<pane ySplit="{$RF}" topLeftCell="{$cell}" activePane="bottomLeft" state="frozen"/>
		</sheetView>
	</sheetViews>

$cell : cell code defined by $CF and $RF
$cell = chr(65 + $CF + 1) . ($RF+1); //for $CF<26
