### ISSUE TITLE
Export Excel not working after hosting the site-unable download

### ISSUE THREAD

**Issue by ChenkieChiu** [shuchkin/simplexlsxgen#65]
@shuchkin 
Dear sir, 
I could run export to excel in localhost server, then I hosted the site, it is only pop-up blank page after I clicked export button. 
```
$cust_name = $_SESSION["cust_name"];
$query = "select * from dbo_order_details WHERE belong_cust = '$cust_name' and user_check = 1 and order_date = DATE(NOW()) order by id";
$result = mysqli_query($conn,$query);
if (mysqli_num_rows($result) > 0) {
    foreach ($result as $row) {
        $id++;
        $Order = array_merge($Order,array(array($row['order_number'],$row['order_date'],$row['expected_date'],$row['deli_storeCode'],$row['deli_storeName'],$row['deli_storeAdd'], $row['item_number'],$row['item_batchNumber'],$row['item_name'],$row['item_grade'],$row['item_EXP'],$row['order_box_qty'],$row['order_string_qty'],$row['order_bag_qty'],$row['note'],)));
    }
}
// $xlsx = Shuchkin\SimpleXLSXGen::fromArray($Order);
// $xlsx->downloadAs('AsiaCargo.xlsx');
// exit();
// $xlsx->saveAs('AsiaCargo.xlsx'); //This will save the file to your server
echo "<pre>";
print_r($Order);
```

**Comment by shuchkin** [comment]
1) replace
$query = "select * from
with required fields 
$query = "select order_number, order_date, expected_date ...

2) replace
$Order = array_merge($Order, ...
$Order[] = $row;

3) SimpleXLSXGen code 
Shuchkin\SimpleXLSXGen::fromArray($Order)->downloadAs('AsiaCargo,xlsx');
exit(); // stop script

**Comment by shuchkin** [comment]
Please delete any output before downloadAs('AsiaCargo,xlsx');
You're breaking the ZIP/XLSX when out <?php echo $_SESSION["cust_name"];?> or echo "<h1>

**Comment by ChenkieChiu** [comment]
I have enabled debug, like belows. May I change
Fatal error: Uncaught Error: Call to undefined function Shuchkin\mb_strlen() in /home/jorcom/public_html/asiastarwms/SimpleXLSXGen.php:350 Stack trace: #0 /home/jorcom/public_html/asiastarwms/SimpleXLSXGen.php(324): Shuchkin\SimpleXLSXGen->_writeEntry() #1 /home/jorcom/public_html/asiastarwms/SimpleXLSXGen.php(192): Shuchkin\SimpleXLSXGen->_write() #2 /home/jorcom/public_html/asiastarwms/userexport_OrderByDate.php(27): Shuchkin\SimpleXLSXGen->downloadAs() #3 {main} thrown in /home/jorcom/public_html/asiastarwms/SimpleXLSXGen.php on line 350

**Comment by ChenkieChiu** [comment]
DEAR SIR, it is worked. Thanks for help!

**Comment by shuchkin** [comment]
Good luck in the difficult way of the PHP-programmer
