### ISSUE TITLE
Less/smaller then not displaying ("<")

### ISSUE THREAD

**Issue by natenjo** [shuchkin/simplexlsxgen#66]
Great libary!

**ISSUE**
I only have one problem:
- The "smaller than" or "less than" symbol is not working and nothing get's displayed (This symbol: "<")

On the other hand the greater than Symbol is working fine (>)

Code to reproduce:

```
require_once('SimpleXLSXGen.php');

$stack = [];
$row = ['greater than', 'smaller than'];
array_push($stack, $row);
$row = ['>', '<'];
array_push($stack, $row);

$xlsx = SimpleXLSXGen2::fromArray( $stack );
$xlsx->downloadAs("test.xlsx"); //`
```

Output in Excel:

![image](https://user-images.githubusercontent.com/6784659/174306346-09ce3b5a-d169-45a0-8497-28826654534d.png)

I am using the current most up to date version (1.2.13) of simplexlsxgen with PHP 7.4.3

**EXPECTATION**
< gets displayed

Any hints welcome

**Comment by shuchkin** [comment]
see RAW STRINGS
https://github.com/shuchkin/simplexlsxgen#data-types
```php
$stack = [];
$stack[] = ['greater than', 'smaller than'];
$stack[] = ['>', "\0".'<'];

SimpleXLSXGen2::fromArray( $stack )->downloadAs("test.xlsx");
```

"<" detected as "formatted string"

**Comment by natenjo** [comment]
Thank you a lot for this hint!
There still seems to be an issue if there is text following after the "<" (without a blank)

e.g. 
```
$stack = [];
$row = ['20- short term: <6 month'];
$row = str_replace('<',"\0 <",$row); 
array_push($stack, $row);

$xlsx = SimpleXLSXGen2::fromArray( $stack );
$xlsx->downloadAs("test.xlsx"); 
```
results in 
![image](https://user-images.githubusercontent.com/6784659/174639713-41e24eb6-e53e-4126-b508-c677db8d0fff.png)

where when adding a space after the "<" the file will generate "correct"

```
$stack = [];
$row = ['20- short term: <6 month'];
$row = str_replace('<',"\0 < ",$row); 
array_push($stack, $row);

$xlsx = SimpleXLSXGen2::fromArray( $stack );
$xlsx->downloadAs("test.xlsx"); 
```

![image](https://user-images.githubusercontent.com/6784659/174640111-6bf41020-1003-4411-89c7-f460d50b697d.png)

Is there a way to output text after the "<" without a blank? like in `20- short term:  <6 month` ?

**Comment by shuchkin** [comment]
use "\0" as prefix, this is not escape symbol
https://github.com/shuchkin/simplexlsxgen/blob/master/src/SimpleXLSXGen.php#L510
