### ISSUE TITLE
save clear html data as default

### ISSUE THREAD

**Issue by nickemail** [shuchkin/simplexlsxgen#67]
Hi. How can i write clear html without conversion. I maen if tab = "<a href="#">data</a>" - save it the same but in xls or xlsx? Is it posible?

**Comment by shuchkin** [comment]
HTML as data in cells? Use RAW STRINGs https://github.com/shuchkin/simplexlsxgen#data-types

**Comment by nickemail** [comment]
Thank. How it to use if i save from ARRAY?

**Comment by nickemail** [comment]
Thanks. How it save from array? Set RAW for all array rows?

**Comment by shuchkin** [comment]
prefix ```#0``` all values
