### ISSUE TITLE
Ajax example

### ISSUE THREAD

**Issue by x215137** [shuchkin/simplexlsxgen#68]
@ ALL

Just copy the latest source and the example of array2excel.php for test

Found that a random file name will be appear on the 'download as' dialogs box fort confirmation, suppose the file name should be 'file.xlsx' that the example hardcode on it...

Don't know how to solve it... and can someone can help / solve this issue, I think the problem not direct related to the simplexlsgen project but the javascript syntax 

KK

**Comment by shuchkin** [comment]
see updated example
https://github.com/shuchkin/simplexlsxgen#js-array-to-excel-ajax

**Comment by x215137** [comment]
@shuchkin 

It WORK very well, thank you so much for your help

:o)
