### ISSUE TITLE
How to save in to a specific folder the xlsx file generated?

### ISSUE THREAD

**Issue by DBDB01** [shuchkin/simplexlsxgen#70]
I have this code: 
`$xlsx = Shuchkin\SimpleXLSXGen::fromArray( $fields );
 $xlsx->saveAs('request.xlsx');`

How can I save the file in to a specific path?

**Comment by shuchkin** [comment]
hmm
if u want bowser dialog use
$xlsx->downloadAs('request.xlsx'); exit();

if u want save xlsx in server specified path use
$xlsx->saveAs('/backup/request.xlsx');

**Comment by ghalysaqqal** [comment]
Like when click on "Page Layout" in Microsoft excel then click "Sheet Right-to-left".

**Comment by shuchkin** [comment]
> Like when click on "Page Layout" in Microsoft excel then click "Sheet Right-to-left".

https://github.com/shuchkin/simplexlsxgen/issues/81
