### ISSUE TITLE
Simple filter || Autofilter

### ISSUE THREAD

**Issue by donalokeefe** [shuchkin/simplexlsxgen#71]
Hi,

I was hoping you might be able to help. Love the project and I have everything working great.

Is there any way to add a simple filter to a row of columns? 

i.e. add a simply filter button to the each column A-K in row 3.

Even if it involves me making specific changes to my SRC file - happy to do that. 

I just can't find any documentation in general about how I could add this with PHP in the generation of a xlsx file.

Any help would be much appreciated!

Donal

**Comment by shuchkin** [comment]
SimpleXLSXGen 1.2.16
https://github.com/shuchkin/simplexlsxgen
https://c-rex.net/projects/samples/ooxml/e1/Part4/OOXML_P4_DOCX_autoFilter_topic_ID0EIDM4.html#topic_ID0EIDM4

```php
$data = [
    ['autofilter'],
    [1000],
    [2000],
    [3000],
    [4000],
    [5000],
    [1500]
];
$xlsx = SimpleXLSXGen::fromArray($data);

// hack
$xlsx->modTemplate('xl/worksheets/sheet1.xml', '<autoFilter ref="A1:A5"/>');

$xlsx->saveAs('autofilter.xlsx');
```

**Comment by donalokeefe** [comment]
Amazing - thanks so much!
I have this working but I have one issue that arises. 
My code looks like this:
`$xlsx2 = SimpleXLSXGen::fromArray( $reportCells )
    ->setDefaultFont( 'Helvetica Neue' )
    ->setDefaultFontSize( 12 )
    ->setColWidth(1, 6) 
    ->setColWidth(2, 6)
    ->setColWidth(3, 50)
    ->setColWidth(4, 20) 
     ->setColWidth(5, 35)
     ->setColWidth(6, 25)       
     ->setColWidth(7, 25)
     ->setColWidth(8, 25)
     ->setColWidth(9, 35)
     ->setColWidth(10, 30)       
     ->setColWidth(11, 35);    
    // ->mergeCells('A1:I1');
    // ->mergeCells('A2:I2');
     
$xlsx2->modTemplate('xl/worksheets/sheet1.xml', '<autoFilter ref="A4:A100"/>');
$xlsx2->saveAs($saveReportPath.'/'.$projectNameForReport.'.xlsx'); `

If I add the mergeCell commands (which were working before - amending semi colon etc) it causes an error when I now add the autofilter. Without the mergeCells the autofilter works.

Also how would I add two autofilters? i.e. the A column works fine but I can't figure out how to do a B column as well etc

Thanks so much for your help!
Donal

**Comment by shuchkin** [comment]
fixed in 1.2.16
use $xlsx->autoFilter('A2:B10');

**Comment by donalokeefe** [comment]
Thanks so much - sorry I missed that I could just change the column letter and it would run across.

I still seem to have the mergecell issue. Individually the "mergeCells" and "modTemplate" work - but as soon as I have both of them it creates an error in the xlsx file.

I'm looking at the SRC file - could it be something with how the strings are swapped in?

**Comment by Mak-73** [comment]
For me autoFilter don't working in excel and in LibreOffice calc. If I load file with LibreOffice then set the filter and save, when reload it's all ok

**Comment by shuchkin** [comment]
> For me autoFilter don't working in excel and in LibreOffice calc. If I load file with LibreOffice then set the filter and save, when reload it's all ok

pls send generated xlsx

**Comment by shuchkin** [comment]
security error, filter activating after click "Edit anyway"

![Image](https://github.com/user-attachments/assets/84458704-cd9d-4cd3-9b1a-dd6cb1e6ac4b)

**Comment by shuchkin** [comment]
no, it's just Excel's security policy, all downloaded files open in read-only mode

**Comment by shuchkin** [comment]
```php
$data = [
    ['Name', 'Price', 'Count', 'Amount'],
    ['Book 1', 2.22, 4, 2.22 * 4],
    ['Book 2', 45, 1, 45],
    ['Book 3', 150.22, 2, 150.22 * 2]
];
SimpleXLSXGen::fromArray($data)->autoFilter('A1:D4')->saveAs('test_autofilter.xlsx');
```

![Image](https://github.com/user-attachments/assets/474a42eb-40e0-43c7-ae03-d78c23b80dbc)

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen?tab=readme-ov-file#debug

**Comment by Mak-73** [comment]
Ok, I run debug code tomorrow and post the result here, thanks for the help

**Comment by Mak-73** [comment]
No error has been reported from the Debug and file debug.xlsx has been generated

**Comment by shuchkin** [comment]
You've already figured out the problem.
