### ISSUE TITLE
0% not formatted as percent

### ISSUE THREAD

**Issue by natenjo** [shuchkin/simplexlsxgen#72]
When I write 0% it is not interpreted as percent, but as text.
For other percent numbers it works

**Code example:**
```
require_once('SimpleXLSXGen.php');

$stack = [];
$row = ['0 Percent', '0%'];
array_push($stack, $row);
$row = ['1 Percent', '1%'];
array_push($stack, $row);

$xlsx = SimpleXLSXGen::fromArray( $stack );
$xlsx->downloadAs("test.xlsx"); 
```

**Current output:**
![image](https://user-images.githubusercontent.com/6784659/184332787-4444877e-eab4-43da-b946-4babf3d64c7c.png)

**Desired output:**
![image](https://user-images.githubusercontent.com/6784659/184344555-6c3252df-7e42-4ab7-a38c-9fd225c1f5a0.png)

Am I overseeing something or is there an error with 0% ?

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen/blob/master/CHANGELOG.md

**Comment by shuchkin** [comment]
reinstall

**Comment by natenjo** [comment]
Thank you for the new release! This fixes my problem :)
