### ISSUE TITLE
Borders

### ISSUE THREAD

**Issue by Jmarcelo97** [shuchkin/simplexlsxgen#73]
Hello, how are you?
Are borders already supported?

Thanks!

**Comment by shuchkin** [comment]
see 1.3.10
https://github.com/shuchkin/simplexlsxgen#formatting

**Comment by ghalysaqqal** [comment]
It's not working !!

`<style height="20"  border="medium"><center><middle>Example</middle></center></style>`

**Comment by shuchkin** [comment]
> It's not working !! I tried with multiple examples but same
> 
> example : `<style height="20" border="medium"><center><middle>Example</middle></center></style>`

check version!

**Comment by ghalysaqqal** [comment]
Working fine, I was using 1.2 version.
thank you.

**Comment by ghalysaqqal** [comment]
Can we do border with merged cells ?

**Comment by shuchkin** [comment]
> Can we do border with merged cells ?

try

**Comment by ghalysaqqal** [comment]
Success

**Comment by guarenty** [comment]
@ghalysaqqal 

How do you do border and merged cells? It is not working for me. When I merge cells with borders it gets weird. 

When all cells except the first are 'null':
<img width="212" alt="image" src="https://user-images.githubusercontent.com/78699517/214850424-09072b9f-7db4-4a07-a29a-f57667a1d328.png">

When all cells have the same value:
<img width="151" alt="image" src="https://user-images.githubusercontent.com/78699517/214852129-d87ba8f6-3d03-4524-9c42-4950dbcc4a48.png">

What am I doing wrong?

**Comment by shuchkin** [comment]
paste your code

**Comment by shuchkin** [comment]
anyway any design in top/left cell, use it for formatting

**Comment by guarenty** [comment]
Thanks for your fast response. Here is my code: 

```
    $array = [
        ['<style height="20" border="medium">Example</style>', 1, 2],
        [null, 3, 4],
        [null, 3, 4],
        [null, 3, 4],
        [null, 3, 4],
        [null, 3, 4]
    ];

    // init xlsx
    $xlsx = Shuchkin\SimpleXLSXGen::fromArray($array, 'Übersicht');

    // merg cells
    $xlsx->mergeCells('A1:A4');
```

Interesting to note is that the Preview of the File is correct. Also when I view it with spacebar on Mac:
<img width="235" alt="image" src="https://user-images.githubusercontent.com/78699517/214901245-148d2f30-ee90-47e3-af98-76ec20c0db4f.png">


Also tried it on windows, same result.

**Comment by shuchkin** [comment]
Draw all borders in merged cells
```php
$array = [
    ['<style height="20" border="medium medium none medium">Example</style>', 1, 2],
    ['<style border="none medium none medium"> </style>', 3, 4],
    ['<style border="none medium none medium"> </style>', 3, 4],
    ['<style border="none medium medium medium"> </style>', 3, 4],
    [null, 3, 4],
    [null, 3, 4]

];

// init xlsx
$xlsx = Shuchkin\SimpleXLSXGen::fromArray($array, 'Übersicht');

// merg cells
$xlsx->mergeCells('A1:A4');
$xlsx->saveAs('test_border_and_merge_cells.xlsx');
```
<img width="144" alt="Screenshot_751" src="https://user-images.githubusercontent.com/315872/214908755-553db0df-3da2-4f30-8b71-0dba5d1f1204.png">

**Comment by guarenty** [comment]
I copied the code u provided and it still won't work: 
<img width="208" alt="image" src="https://user-images.githubusercontent.com/78699517/214915801-110f7029-c4bc-42a0-9177-ad1b8c28c723.png">

In your picture I can't tell if the left border is drawn correctly or not.

**Comment by shuchkin** [comment]
> I copied the code u provided and it still won't work: <img alt="image" width="208" src="https://user-images.githubusercontent.com/78699517/214915801-110f7029-c4bc-42a0-9177-ad1b8c28c723.png">
> 
> In your picture I can't tell if the left border is drawn correctly or not.

<img width="357" alt="Screenshot_752" src="https://user-images.githubusercontent.com/315872/214928956-649f3373-0ee5-4889-880d-637983e5b681.png">

**Comment by shuchkin** [comment]
> I tested a little more. It is working fine when I merge cells that are not on the Edge. But still I have to define the borders in every cell I merge and can't just set the cells 'null'. I think it would be easier when it just uses the border defined in the top/left cell.

I agree, just "borders" is a relatively new feature

**Comment by guarenty** [comment]
Testet it again with a different setup, still no different result.
Thanks for looking into it.
I think I can get it to work for my needs.

**Comment by guarenty** [comment]
now it magically works on windows, Mac (Numbers) still same problem.
