### ISSUE TITLE
null in cell does not get merged

### ISSUE THREAD

**Issue by infotts-jfq** [shuchkin/simplexlsxgen#75]
In your exemple, you say that this should produce two cell merged :
['<center>MERGE CELLS MERGE CELLS MERGE CELLS MERGE CELLS MERGE CELLS</center>', null]

But for some reason, it does not ?

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen#formatting
see screenshot

**Comment by infotts-jfq** [comment]
> https://github.com/shuchkin/simplexlsxgen#formatting see screenshot

Yes I understand, but look, I tested the same data as in your $data variable and this is what I get.
See my screenshot here : [](https://ibb.co/hYp6f98)

Everything is ok except the merging of cells.

**Comment by infotts-jfq** [comment]
This is the exact php code to reproduce the problem I get. Maybe I am doing something wrong also, I don't know.

`<?php
include_once("simplexlsxgen.php");
$data = [
    ['Normal', '12345.67'],
    ['Bold', '<b>12345.67</b>'],
    ['Italic', '<i>12345.67</i>'],
    ['Underline', '<u>12345.67</u>'],
    ['Strike', '<s>12345.67</s>'],
    ['Bold + Italic', '<b><i>12345.67</i></b>'],
    ['Hyperlink', 'https://github.com/shuchkin/simplexlsxgen'],
    ['Italic + Hyperlink + Anchor', '<i><a href="https://github.com/shuchkin/simplexlsxgen">SimpleXLSXGen</a></i>'],
    ['Green', '<style color="#00FF00">12345.67</style>'],
    ['Bold Red Text', '<b><style color="#FF0000">12345.67</style></b>'],
    ['Blue Text and Yellow Fill', '<style bgcolor="#FFFF00" color="#0000FF">12345.67</style>'],
    ['Left', '<left>12345.67</left>'],
    ['Center', '<center>12345.67</center>'],
    ['Right', '<right>Right Text</right>'],
    ['Center + Bold', '<center><b>Name</b></center>'],
    ['Row height', '<style height="50">Row Height = 50</style>'],
    ['Top', '<style height="50"><top>Top</top></style>'],
    ['Middle + Center', '<style height="50"><middle><center>Middle + Center</center></middle></style>'],
    ['Bottom + Right', '<style height="50"><bottom><right>Bottom + Right</right></bottom></style>'],
    ['<center>MERGE CELLS MERGE CELLS MERGE CELLS MERGE CELLS MERGE CELLS</center>', null],
    ['<top>Word wrap</top>', "<wraptext>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book</wraptext>"]
];
$xlsx = new Shuchkin\SimpleXLSXGen();
$xlsx->addSheet($data,"test");
$xlsx->downloadAs('test.xlsx');
exit()
?>`

**Comment by shuchkin** [comment]
see ->mergeCells(....) method
```php
SimpleXLSXGen::fromArray( $data )
    ->setDefaultFont( 'Courier New' )
    ->setDefaultFontSize( 14 )
    ->setColWidth(1, 35) // 1 - num column, 35 - size in chars
    ->mergeCells('A20:B20')
    ->saveAs('styles_and_tags.xlsx');
```

**Comment by infotts-jfq** [comment]
Yes the mergeCells() method works. I wanted to try the nullable cell to see if it would fix the other problem I have but since it does not work, I will have to try an other way.

I have a cell in column A with a very long text (the last one), I don't want the column A to be resized as large as this cell, but I want the column A to be resized as large as the largest text (except of that largest one).
So I wanted to merge those cells in the last row to see if it would stop from resizing column A to that last row size.
Anyway, I guess I will have to check what is the longest text in column A and resize the column A manually for that text.

btw, thanks for correcting the code in my last post ;)

**Comment by shuchkin** [comment]
use ->setColWidth(1, 35)
