### ISSUE TITLE
Line merging

### ISSUE THREAD

**Issue by aardabalkan** [shuchkin/simplexlsxgen#76]
Hello,

Is it possible to merge lines in some columns. For example, I want to merge B2 and C2 only. B1 and C1, B3 and C3 will not merged.

**Comment by shuchkin** [comment]
```php
$xlsx->mergeCells('B2:C2');
$xlsx->mergeCells('B1:C1');
```

**Comment by aardabalkan** [comment]
Thank you for the response Shuchkin, SimpleXLS is wonderful. Thank you so much!
