### ISSUE TITLE
Rest of the html codes merged into the Excel file

### ISSUE THREAD

**Issue by pauliu749** [shuchkin/simplexlsxgen#77]
HI,

simplexlsxgen is great! Thank you very much ^^

I found a minor problem, I used the example code and added a small portion of html code at the end of the php file, the xlsx file it saved will included those html code at the end of the xlsx file, as a result Excel will show the file is corrupted and need to be repaired when open.

`&lt;?php

require 'simplexlsxgen.php';

$books = [
  ['ISBN', 'title', 'author', 'publisher', 'ctry' ],
  [618260307, 'The Hobbit', 'J. R. R. Tolkien', 'Houghton Mifflin', 'USA'],
  [908606664, 'Slinky Malinki', 'Lynley Dodd', 'Mallinson Rendel', 'NZ']
];
$xlsx = Shuchkin\SimpleXLSXGen::fromArray( $books );
$xlsx-&gt;downloadAs('books.xlsx');

?&gt;
&lt;html&gt;
  &lt;head&gt;
    &lt;title&gt;
      Testing
    &lt;/title&gt;
  &lt;/head&gt;
  &lt;body&gt;
    Testing
  &lt;/body&gt;
&lt;/html&gt;`

[books (26).xlsx](https://github.com/shuchkin/simplexlsxgen/files/9771115/books.26.xlsx)

**Comment by shuchkin** [comment]
remove any output before and after downloadAs
or use `exit`

**Comment by pauliu749** [comment]
"exit" solved the problem! Thanks a lot!
