### ISSUE TITLE
Set cell type

### ISSUE THREAD

**Issue by vhanadium** [shuchkin/simplexlsxgen#82]
Hi,

I need to set a cell to monetary type but I don't seem to find how ?
Is that even possible ?

Thanck you

**Comment by shuchkin** [comment]
Use raw strings https://github.com/shuchkin/simplexlsxgen#data-types

**Comment by vhanadium** [comment]
Hi, your solution don't make the cell as monetary but as a string.
In Excel you can choose to put a cell as Monetary with money symbol.
Is that possible with your library please ?

**Comment by vhanadium** [comment]
I dug on what you said and in the official MS Excel documentation there's no reference to monetary format:
[https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1](url)

What am I missing please ?

**Comment by vhanadium** [comment]
And I tried to change the "\0" to "\1" or "\2" and got errors in Excel.
I really don't understand when you meant.

**Comment by vhanadium** [comment]
Ok found out I have to modify your script to add currency type of xf numFmtId to 5

**Comment by vhanadium** [comment]
I figured it out, it's not 5 but 7 for decimal
add this:
`const N_CURRENCY = 7; // 0.00 €`
And
`                            } elseif ( preg_match( '/^[+-]?[0-9]{1,3}(?:,?[0-9]{3})*\.[0-9]{2}\ ?\p{Sc}$/u', $v, $m ) ) {
                                if ( strlen( $m[2] ) < 3 ) {
                                    $cv = preg_replace('~[.,](?=\d{2}\b)|\p{Sc}~u', '#', $v);
                                    $cv = strtr(rtrim($cv, '#'), ['#' => '.', '.' => '', ',' => '']);
                                    $N = self::N_CURRENCY; // [5] 0.00€
                                }
                            }`
