### ISSUE TITLE
Hyperlink to another sheet

### ISSUE THREAD

**Issue by duduluiz** [shuchkin/simplexlsxgen#83]
Hello there,

How works hyperlink or formulas inside xlsx. Example: HYPERLINK("sheet1!a1";"click me")?

Regards!

**Comment by shuchkin** [comment]
Hyperlinks inside Excel not supported for now

**Comment by shuchkin** [comment]
wait pls, I'll release 1.3 today, there works
<a href="sheet1!a1">link text</a>

**Comment by duduluiz** [comment]
\o/ Thank you so mutch

**Comment by shuchkin** [comment]
see 1.3.10
https://github.com/shuchkin/simplexlsxgen#data-types

**Comment by duduluiz** [comment]
Worked the link, but now have a error: SimpleXLSXGen.php (752) Undefined offset: 1"

**Comment by shuchkin** [comment]
> Worked the link, but now have a error: SimpleXLSXGen.php (752) Undefined offset: 1"

what php version, and what string value triggered this error?

**Comment by shuchkin** [comment]
fixed

**Comment by duduluiz** [comment]
what php version: **7.3.29**

 and what string value triggered this error? **1.28.632**

**Comment by duduluiz** [comment]
Success! Thank you very much
