### ISSUE TITLE
Can you change the font type and size

### ISSUE THREAD

**Issue by sarelvdm** [shuchkin/simplexlsxgen#84]
Hi,

How do you change the font type and size

**Comment by shuchkin** [comment]
https://github.com/shuchkin/simplexlsxgen#formatting
setDefaultFont
setDefaultFontSize

**Comment by sarelvdm** [comment]
> https://github.com/shuchkin/simplexlsxgen#formatting setDefaultFont setDefaultFontSize

Looking to change individual row / columns font and size. Thanks for replying
