### ISSUE TITLE
1.3.10 bug

### ISSUE THREAD

**Issue by erkkki** [shuchkin/simplexlsxgen#85]
> Fatal error: Array and string offset access syntax with curly braces is no longer supported in /app/vendor/shuchkin/simplexlsxgen/src/SimpleXLSXGen.php on line 648

Pipelin broke in 1.3.10, reversing back to 1.2.* works fine.

**Comment by duduluiz** [comment]
after, the xlsx files have errors:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <logFileName>error051000_01.xml</logFileName>
  <repairedRecords>
    <repairedRecord>Repaired Records: Information about the cell of part of /xl/worksheets/sheet1.xml</repairedRecord>
    <repairedRecord>Repaired Records: Information about the cell of part of /xl/worksheets/sheet6.xml</repairedRecord>
  </repairedRecords>
</recoveryLog>

**Comment by duduluiz** [comment]
after, the xlsx files have errors:

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <logFileName>error051000_01.xml</logFileName>
  <repairedRecords>
    <repairedRecord>Repaired Records: Information about the cell of part of /xl/worksheets/sheet1.xml</repairedRecord>
    <repairedRecord>Repaired Records: Information about the cell of part of /xl/worksheets/sheet6.xml</repairedRecord>
  </repairedRecords>
</recoveryLog>`

**Comment by shuchkin** [comment]
fixed
