### ISSUE TITLE
setColWidth with AutoWidth

### ISSUE THREAD

**Issue by g-pane** [shuchkin/simplexlsxgen#88]
Hi,
Is possibile to set the autowidth (to the column) based on text size?
With the default parameters and some style (using fromArray function) i see the text truncated:
![image](https://user-images.githubusercontent.com/71759818/211816302-dc765aaa-d6ee-4585-92ca-9f00a9bd1fbc.png)

Thanks for the library, very useful

**Comment by shuchkin** [comment]
autowidth is default
don't use setColWidth

**Comment by g-pane** [comment]
The default don't set the autowidth correctly, see the screenshot

**Comment by shuchkin** [comment]
```php
$xlsx = SimpleXLSXGen::fromArray($rows);
// finding longest strings in columns
$cols = array_fill(0, count($rows[0]), 0); // [0,0,0,....] 
foreach( $rows as $r ) {
    foreach( $r as $k => $v ) {
        $len = strlen( $v ); // may be striptags if used?
        if ( $len > $cols[$k] ) {
            $cols[$k] = $len;
        }
    }
}
foreach( $cols as $k => $v ) {
    $xlsx->setColWidth( $k, $v + 10 ); // $v + 10 is colwidth in chars 
}
$xlsx->saveAs( 'mycolwidth.xlsx' );
```

**Comment by g-pane** [comment]
It works. I'll suggest (feature request) to make a separate function for this, like:
`SimpleXLSXGen::autoWidth($rows, 10)`
With a parameter for make the +10 (i have make +3)
