### ISSUE TITLE
Font size for single cell

### ISSUE THREAD

**Issue by g-pane** [shuchkin/simplexlsxgen#91]
How to make font style (size, type) for the single cell?
Thanks

**Comment by shuchkin** [comment]
1.3.10 not supported

**Comment by g-pane** [comment]
When will be supported?

**Comment by setro-ru** [comment]
we are very much waiting, we really need it

**Comment by shuchkin** [comment]
if u have time and knowledge, then write and share code for individual fonts
if u have money, support project https://opencollective.com/simplexlsx for my motivation
else
wait (may be next week) or try alternative library

**Comment by g-pane** [comment]
I have starred the project, everyone that use the library must do it. I'll wait the next week, i like your library so we want to use it

**Comment by g-pane** [comment]
@shuchkin any news? Thanks again for your work!

**Comment by g-pane** [comment]
News?

**Comment by mrjemson** [comment]
Have added a font-size style attribute into my fork and submitted a pull request.
https://github.com/mrjemson/simplexlsxgen

Works for my purposes, by YMMV.
![image](https://user-images.githubusercontent.com/10329974/229038524-1f83d46f-48a2-433f-aa5a-9d6349e0f3bf.png)

**Comment by shuchkin** [comment]
```<style font-size="32">Big Text</style>```
1.3.12
