### ISSUE TITLE
special charecters Issue when  trying to read data from excel

### ISSUE THREAD

**Issue by developeralim** [shuchkin/simplexlsxgen#95]
I am trying to read xlsxl file. in one field of the file has special charecters .value of that field is coming without special charecters by changing original value. what is the solution?

code example :

                  if ( $xlsx = SimpleXLSX::parse($xlsxFile) ) {
                        echo '<pre>';
                        print_r( $xlsx->rows() );
                  } else {
                        echo SimpleXLSX::parseError();
                  }

output:
![image](https://user-images.githubusercontent.com/95765755/216937219-e4333e88-ad57-4689-8ee1-cbdf798ccaf9.png)

expected : 
![image](https://user-images.githubusercontent.com/95765755/216937458-3dd9b082-5e85-47f1-a949-d185e40af558.png)

**Comment by shuchkin** [comment]
pls send xlsx example
and try ```$xlsx->rowsEx()``` to detect %

**Comment by developeralim** [comment]
Thank you its working
