### ISSUE TITLE
Merging more than one Cell

### ISSUE THREAD

**Issue by oricosta88** [shuchkin/simplexlsxgen#96]
Hi, I have an issue I need to merge more than one or two columns is this even possible with this library, i'm trying something like this to merge: 

$xlsx->mergeCells('B1:C1','C1:D1','E1:F1','F1:G1','G1:H1','J1:K1','K1:L1']);

It does Merge the cells but when i try to center the title or resize it to change the rows below doesn't work
It looks like it only merge the only first one column but the others it only merge visually it don't let me select it as only column merged

**Comment by shuchkin** [comment]
```php
$xlsx->mergeCells('B1:C1')
  ->mergeCells('C1:D1')  // <------ С1?
  ->mergeCells('E1:F1');
```

**Comment by oricosta88** [comment]
I already did it like this, however I tried to use this exact code to see if it works
$xlsx->mergeCells('B1:C1')->mergeCells('C1:D1')->mergeCells('D1:E1');

As you can see in these screenshots the merge it is done right visually but when i select the cell it only selects the B1:C1 merge and ignores the 2 other merges making impossible to interact with them and i needed to interact to display the text in the middle of the cells and also make the cells much small like the D cell and i can't because
![Captura de pantalla de 2023-02-22 09-25-04](https://user-images.githubusercontent.com/126000927/220564417-e08360c6-dd57-4809-9953-9ee5d5d20567.png)
![Select](https://user-images.githubusercontent.com/126000927/220564462-2fd9aef8-07f9-4f1a-95a1-e1968f260699.png)
 the merge

**Comment by shuchkin** [comment]
u can merge any range, why u did 3 merges (plus, there range intersection error)?
```php
$xlsx->mergeCells('A1:E1');
```

**Comment by oricosta88** [comment]
Thank you this worked for me, I have another issue with the border i try to apply it but just dosn't appear
'<style border="#000000" height="20"> </style>'
![Captura de pantalla de 2023-02-22 13-32-24](https://user-images.githubusercontent.com/126000927/220620660-683ee57d-dd0c-4677-b094-14b74c5c62c3.png)

**Comment by shuchkin** [comment]
```php
$data = [
    ['-------', ''],
    ['', '<style border="#000000" bgcolor="#FFFF00"> </style>'],

];
SimpleXLSXGen::fromArray($data)
    ->saveAs('test_b
<img width="221" alt="Screenshot_773" src="https://user-images.githubusercontent.com/315872/220647686-b677bffc-2812-42ce-8de6-4d6c0fc059f6.png">
orders2.xlsx');
```

**Comment by oricosta88** [comment]
I'm doing the same code and still not working
![Captura de pantalla de 2023-02-22 16-25-49](https://user-images.githubusercontent.com/126000927/220669267-573ce505-b7ee-4371-85ab-a61ddf540a59.png)
![Captura de pantalla de 2023-02-22 16-24-53](https://user-images.githubusercontent.com/126000927/220669316-cc633ae4-856e-4cd4-a2f7-c5832e2165a4.png)

**Comment by shuchkin** [comment]
u need remove spaces around 908606664

**Comment by shuchkin** [comment]
don't forget [simplexlsxgen is opensource](https://opencollective.com/simplexlsx)
