### ISSUE TITLE
Only works with UTF-8 data

### ISSUE THREAD

**Issue by paulstenning** [shuchkin/simplexlsxgen#97]
Not really an issue but it would be worth noting in README.md that this only works with UTF-8 data. If the data is a different character set such as ISO-8859-1 the spreadsheet is still created but is corrupted and unusable.

In my case (legacy system using PHP 7.0) the following code fixed it:

`array_walk_recursive($data, function (&$item) {
	$item = mb_convert_encoding($item, 'UTF-8', 'ISO-8859-1');
});`

With PHP 7.2 or later mb_convert_encoding() handles arrays directly,

**Comment by shuchkin** [comment]
<img width="731" alt="Screenshot_774" src="https://user-images.githubusercontent.com/315872/221335004-43da7df5-d6ad-4e38-91fc-310c55ab9c45.png">

**Comment by paulstenning** [comment]
This also applies to currency, formula, hyperlink, internal link, raw string etc (which isn't stated in the examples). I think it would be useful to have a note in README.md that ALL data must be UTF-8 just to avoid confusion. Thank you. :)

**Comment by shuchkin** [comment]
<img width="733" alt="Screenshot_776" src="https://user-images.githubusercontent.com/315872/221353870-994855c9-b1ba-4d8c-b80d-62555ace7dcb.png">
